typography_spectrum: 0.7665781388059258
color:
  saturation: 0.8396022494416684
  brandStrength: 0.28985701221972704
  lightness: 0.31380879669450223
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  rhythmicContrast: 0.06728806695900857
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.050613515777513385
analytics:
  twitter: null
  google: null
  facebook: null
author:
  name: Alexandra Petrova
  email: Info@AB-Photography.us
  url: 'http://www.ab-photography.us/'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a123a4a4-4afc-4af2-acf1-3b4527b415f9.png
name: AB-Photography
cta:
  bucket: null
  version: null
  domain: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/c5d46bb7-a1d3-4214-8d3a-ae77b2e0d9e1.ico
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: AB-Photography.us
purpose: []
